# Copyright (c) 2026 MatyanKass. All rights reserved.
# The sound effects are generated by arithmetic, so they can go wrong silently: a bad
# envelope or a sign error gives a stream that exists but is inaudible or clipped solid.
extends RefCounted

var failures: Array[String] = []
var checks: int = 0

func expect(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures.append(message)

# by MatyanKass
func test_every_effect_renders_to_real_audio() -> void:
	var sfx = load("res://src/ui/sfx.gd").new()
	for name in sfx.RECIPES:
		var stream: AudioStreamWAV = sfx._render(sfx.RECIPES[name])
		expect(stream.data.size() > 0, "%s produced no samples" % name)
		expect(stream.mix_rate == sfx.RATE, "%s came out at the wrong rate" % name)
		var peak := 0
		var silent_run := 0
		var longest_silence := 0
		for i in range(0, stream.data.size(), 2):
			var sample := stream.data[i] | (stream.data[i + 1] << 8)
			if sample >= 32768:
				sample -= 65536
			peak = maxi(peak, absi(sample))
			if absi(sample) < 8:
				silent_run += 1
				longest_silence = maxi(longest_silence, silent_run)
			else:
				silent_run = 0
		expect(peak > 2000, "%s is too quiet to hear (peak %d)" % [name, peak])
		expect(peak <= 32767, "%s clips (peak %d)" % [name, peak])
		# A sound that is mostly silence means the envelope killed it immediately.
		var samples := stream.data.size() / 2
		expect(longest_silence < samples * 3 / 4,
			"%s is silence with a blip in it" % name)
	sfx.free()

func test_a_supplied_file_would_replace_the_generated_one() -> void:
	var sfx = load("res://src/ui/sfx.gd").new()
	# Nothing is supplied yet, so every effect must fall back to the synthesiser rather
	# than to silence. The point of the test is that the lookup runs at all: a typo in
	# the folder name would go unnoticed until someone dropped a file in and it did
	# nothing.
	for name in sfx.RECIPES:
		var supplied = sfx.load_override(str(name))
		expect(supplied == null or supplied is AudioStream,
			"%s must resolve to a real stream or to nothing" % name)
	expect(sfx.load_override("no_such_effect") == null,
		"an effect nobody has supplied a file for resolves to nothing")
	# Case is not part of the name: a file called Build.ogg is the build sound.
	expect(sfx.load_override("BUILD") == sfx.load_override("build"),
		"the lookup must ignore case, or a capital letter silently loses the file")
	sfx.free()

# by MatyanKass
func test_supplied_files_actually_reach_the_player() -> void:
	# Whatever is sitting in assets/sfx right now has to load. A file with the wrong
	# extension for what is inside it - an Ogg named .mp3, say - would fail here rather
	# than in someone's ears.
	var sfx = load("res://src/ui/sfx.gd").new()
	var dir := DirAccess.open(sfx.OVERRIDE_DIR)
	if dir == null:
		sfx.free()
		return
	for file in dir.get_files():
		var clean := file.trim_suffix(".import")
		var is_audio := false
		for suffix in sfx.OVERRIDE_TYPES:
			if clean.to_lower().ends_with(suffix):
				is_audio = true
		if not is_audio:
			continue
		var name := clean.substr(0, clean.rfind("."))
		expect(sfx.RECIPES.has(name.to_lower()),
			"%s does not match any effect name, so nothing will ever play it" % clean)
		expect(sfx.load_override(name) != null, "%s failed to load" % clean)
	sfx.free()

func test_effects_are_short_enough_to_spam() -> void:
	var sfx = load("res://src/ui/sfx.gd").new()
	# Capture fires as fast as the cooldown allows, so its sound must fit inside the
	# shortest gap between two captures or the effects would pile up on each other.
	var capture: AudioStreamWAV = sfx._render(sfx.RECIPES["capture"])
	var seconds := float(capture.data.size() / 2) / float(sfx.RATE)
	var cooldown := float(Balance.CAPTURE_COOLDOWN_TICKS) / float(Balance.TICKS_PER_SECOND)
	expect(seconds <= cooldown, "the capture sound (%.2fs) outlasts its cooldown (%.2fs)"
		% [seconds, cooldown])
	sfx.free()
