# The sound effects are generated by arithmetic, so they can go wrong silently: a bad
# envelope or a sign error gives a stream that exists but is inaudible or clipped solid.
extends RefCounted

var failures: Array[String] = []
var checks: int = 0

func expect(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures.append(message)

func test_every_effect_renders_to_real_audio() -> void:
	var sfx = load("res://src/ui/sfx.gd").new()
	for name in sfx.RECIPES:
		var stream: AudioStreamWAV = sfx._render(sfx.RECIPES[name])
		expect(stream.data.size() > 0, "%s produced no samples" % name)
		expect(stream.mix_rate == sfx.RATE, "%s came out at the wrong rate" % name)
		var peak := 0
		var silent_run := 0
		var longest_silence := 0
		for i in range(0, stream.data.size(), 2):
			var sample := stream.data[i] | (stream.data[i + 1] << 8)
			if sample >= 32768:
				sample -= 65536
			peak = maxi(peak, absi(sample))
			if absi(sample) < 8:
				silent_run += 1
				longest_silence = maxi(longest_silence, silent_run)
			else:
				silent_run = 0
		expect(peak > 2000, "%s is too quiet to hear (peak %d)" % [name, peak])
		expect(peak <= 32767, "%s clips (peak %d)" % [name, peak])
		# A sound that is mostly silence means the envelope killed it immediately.
		var samples := stream.data.size() / 2
		expect(longest_silence < samples * 3 / 4,
			"%s is silence with a blip in it" % name)
	sfx.free()

func test_effects_are_short_enough_to_spam() -> void:
	var sfx = load("res://src/ui/sfx.gd").new()
	# Capture fires as fast as the cooldown allows, so its sound must fit inside the
	# shortest gap between two captures or the effects would pile up on each other.
	var capture: AudioStreamWAV = sfx._render(sfx.RECIPES["capture"])
	var seconds := float(capture.data.size() / 2) / float(sfx.RATE)
	var cooldown := float(Balance.CAPTURE_COOLDOWN_TICKS) / float(Balance.TICKS_PER_SECOND)
	expect(seconds <= cooldown, "the capture sound (%.2fs) outlasts its cooldown (%.2fs)"
		% [seconds, cooldown])
	sfx.free()
